name: Lint

on:
  push:
    branches: [ "master","dev" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master","dev" ]

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: "Install dependencies and run tests"
        run: |
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99
          npm install eslint stylelint eslint-plugin-prettier prettier
          npm run lint:js
          npm run lint:css